<?php
session_save_path(__DIR__ . '/sessions');
session_start();
if(!isset($_SESSION['user_id'])) exit("noauth");
$me = (int)$_SESSION['user_id'];
$conv = (int)($_POST['c'] ?? 0);
if(!isset($_FILES['image'])) exit("noimg");
$ext = pathinfo($_FILES['image']['name'], PATHINFO_EXTENSION);
$fname = time()."_".bin2hex(random_bytes(4)).".".$ext;
move_uploaded_file($_FILES['image']['tmp_name'], __DIR__."/chat_images/".$fname);
$mysqli = new mysqli("localhost","root","","empresa");
$stmt = $mysqli->prepare("SELECT user1,user2 FROM conversaciones WHERE id=?");
$stmt->bind_param("i",$conv);
$stmt->execute();
$c = $stmt->get_result()->fetch_assoc();
$receptor = ($c['user1']==$me)?$c['user2']:$c['user1'];
$stmt = $mysqli->prepare("INSERT INTO mensajes (conversacion_id, remitente_id, receptor_id, imagen, enviado, leido) VALUES (?,?,?,?,NOW(),0)");
$stmt->bind_param("iiis",$conv,$me,$receptor,$fname);
$stmt->execute();
echo "ok";
